language: rust

matrix:
  include:
    - rust: stable
    - rust: nightly
      env: CLIPPY
      script: |
        if rustup component add clippy-preview; then
            cargo clippy -- -Dclippy
        fi

script:
  - cargo build
  - cargo test
